const authRestaurante = require('../middlewares/authRestaurante');
const checkPermissao = require('../middlewares/checkPermissao');
const { requirePlanFeature } = require('../middlewares/requirePlanFeature');
const express = require('express');
const router = express.Router();
const c = require('../controllers/caixaController');
router.use(authRestaurante);
router.param('restauranteId', (req,res,next,value)=>{
  if(String(req.restauranteId)!==String(value)) return res.status(403).json({code:'RESTAURANTE_MISMATCH',message:'Restaurante não autorizado.'});
  next();
});
router.get('/:restauranteId/operadores', c.listarOperadores);
router.post('/:restauranteId/operadores', checkPermissao('gerenciarOperadores'), c.salvarOperador);
router.put('/:restauranteId/operadores/:operadorId', checkPermissao('gerenciarOperadores'), c.salvarOperador);
router.patch('/:restauranteId/operadores/:operadorId/status', checkPermissao('gerenciarOperadores'), c.alternarOperador);
router.get('/:restauranteId/atual', c.caixaAtual);
router.post('/:restauranteId/abrir', checkPermissao('abrirCaixa'), c.abrirCaixa);
router.post('/:restauranteId/movimento', checkPermissao('movimentarCaixa'), c.movimentarCaixa);
router.post('/:restauranteId/fechar', checkPermissao('fecharCaixa'), c.fecharCaixa);
router.get('/:restauranteId/relatorios', checkPermissao('visualizarRelatorios'), requirePlanFeature('salesReports'), c.relatorios);
module.exports = router;
