const express = require("express");
const router = express.Router();
const mp = require("../controllers/mercadoPagoController");
const authRestaurante = require('../middlewares/authRestaurante');
const { requirePlanFeature } = require('../middlewares/requirePlanFeature');
router.get("/oauth/start/:restauranteId", mp.startOAuth);
router.get("/oauth/callback", mp.callbackOAuth);
router.get("/status/:restauranteId", mp.statusById);
router.post("/disconnect", authRestaurante, requirePlanFeature("onlinePayments"), mp.disconnect);
module.exports = router;
