CREATE TABLE IF NOT EXISTS clientes_mensalistas (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  restauranteId VARCHAR(24) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  telefone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NULL,
  documento VARCHAR(255) NULL,
  endereco LONGTEXT NULL,
  diaVencimento DOUBLE NULL,
  limiteCredito DECIMAL(12,2) NULL,
  status VARCHAR(255) NULL,
  observacoes TEXT NULL,
  criadoPor VARCHAR(24) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_clientes_mensalistas_rest_telefone (restauranteId, telefone(191)),
  KEY idx_clientes_mensalistas_restaurante (restauranteId),
  KEY idx_clientes_mensalistas_status (restauranteId, status(32))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contas_receber (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  restauranteId VARCHAR(24) NOT NULL,
  clienteMensalistaId VARCHAR(24) NOT NULL,
  pedidoId VARCHAR(24) NULL,
  descricao TEXT NULL,
  competencia VARCHAR(255) NULL,
  numeroParcela DOUBLE NULL,
  totalParcelas DOUBLE NULL,
  valorOriginal DECIMAL(12,2) NULL,
  saldo DECIMAL(12,2) NULL,
  vencimento DATETIME NULL,
  status VARCHAR(255) NULL,
  observacoes TEXT NULL,
  criadoPor VARCHAR(24) NULL,
  canceladoEm DATETIME NULL,
  canceladoPor VARCHAR(24) NULL,
  motivoCancelamento TEXT NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  KEY idx_contas_receber_restaurante (restauranteId),
  KEY idx_contas_receber_cliente (restauranteId, clienteMensalistaId),
  KEY idx_contas_receber_vencimento (restauranteId, vencimento),
  KEY idx_contas_receber_status (restauranteId, status(32)),
  KEY idx_contas_receber_pedido (restauranteId, pedidoId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recebimentos_conta (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  restauranteId VARCHAR(24) NOT NULL,
  contaReceberId VARCHAR(24) NOT NULL,
  clienteMensalistaId VARCHAR(24) NOT NULL,
  valor DECIMAL(12,2) NULL,
  metodo VARCHAR(255) NULL,
  recebidoEm DATETIME NULL,
  caixaSessaoId VARCHAR(24) NULL,
  caixaMovimentoId VARCHAR(24) NULL,
  operadorId VARCHAR(24) NULL,
  observacoes TEXT NULL,
  idempotencyKey VARCHAR(255) NULL,
  criadoPor VARCHAR(24) NULL,
  status VARCHAR(255) NULL,
  estornadoEm DATETIME NULL,
  estornadoPor VARCHAR(24) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_recebimentos_conta_idempotencia (restauranteId, idempotencyKey(120)),
  KEY idx_recebimentos_conta_restaurante (restauranteId),
  KEY idx_recebimentos_conta_conta (contaReceberId),
  KEY idx_recebimentos_conta_cliente (restauranteId, clienteMensalistaId),
  KEY idx_recebimentos_conta_data (restauranteId, recebidoEm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
