require('dotenv').config();
require('../models/Restaurante');
require('../models/CategoriaProduto');
require('../models/Produto');
require('../models/Pedido');
require('../models/Cliente');
require('../models/Entregador');
require('../models/EntregadorOnline');
require('../models/mesaModel');
require('../models/pedidoMesaModel');
require('../models/Frete');
require('../models/Insumo');
require('../models/MovimentoEstoque');
require('../models/Receita');
require('../models/OAuthState');
require('../models/ImagemFavorita');
require('../models/Adicional');
require('../models/Borda');
require('../models/Complemento');
require('../models/Sabor');
const { testConnection } = require('../db/mysql');
const { syncAllModels } = require('../lib/mysqlModelFactory');
(async()=>{ await testConnection(); await syncAllModels(); console.log('✅ Tabelas MySQL sincronizadas coluna por coluna.'); process.exit(0); })().catch(e=>{ console.error(e); process.exit(1); });
