const money={type:'DECIMAL(12,2)',kind:'number'}, num={type:'DOUBLE',kind:'number'}, bool={type:'TINYINT(1)',kind:'boolean'}, str={type:'VARCHAR(255)'}, txt={type:'TEXT'}, date={type:'DATETIME',kind:'date'}, id={type:'VARCHAR(24)',kind:'id'}, json={type:'LONGTEXT',kind:'json',json:true};
module.exports = {

  AdminSaas:{table:'admins', fields:{nome:str,email:str,senha:str,tipo:str,ativo:bool,ultimoLoginEm:date}, defaults:{ativo:true,tipo:'full'}, indexes:['CREATE UNIQUE INDEX idx_admins_email ON admins (email(191))']},

  PlanoSaas:{table:'planos_saas', fields:{codigo:str,nome:str,valorMensal:money,descricao:txt,recursos:json,ativo:bool,ordem:num}, defaults:{ativo:true,valorMensal:0,recursos:[],ordem:0}, indexes:['CREATE UNIQUE INDEX idx_planos_saas_codigo ON planos_saas (codigo(191))']},

  Restaurante:{table:'restaurantes', fields:{nome:str,email:str,senha:str,cnpj:str,enderecoCep:str,enderecoRua:str,enderecoNumero:str,enderecoBairro:str,enderecoCidade:str,enderecoEstado:str,telefone:str,logoUrl:txt,logoSlug:str,horariosFuncionamento:json,tempoMedioEntregaMin:num,tempoAutoCancelamentoVitrineMin:num,maxPedidosPorEntregador:num,pedidosPorEntregador:num,anotaaiStatus:bool,anotaaiUrl:txt,anotaaiIdentificador:str,anotaaiToken:txt,ifoodStatus:bool,ifoodIdentificador:str,ifoodPrecisaConfirmacao:bool,ifoodIgnorarPronto:bool,ifood:json,localizacao:json,statusBot:json,ativo:bool,mensagensPersonalizadas:json,chavePix:str,recipient_id:str,mercadoPago:json,pagamentoCartaoAtivo:bool,taxaCartaoCreditoAvistaPercent:money,taxaConvenienciaPix:money,descontoMensalidadePercentual:money,valorMensalidadeCustomizado:money,garcons:json,plano:str,statusAssinatura:str,dataInicioPlano:date,dataFimPlano:date,observacaoPlano:txt,emailCobranca:str,cancelamentoPlanoEm:date,cancelamentoPlanoMotivo:txt,cancelamentoPlanoEstornoStatus:str,cancelamentoPlanoEstornoValor:money,cancelamentoPlanoDetalhes:json,ultimoResetSenhaEm:date,sessaoVersao:num,slugIdentificador:str,dataCadastro:date}, defaults:{ativo:true,plano:'free',statusAssinatura:'ativo',sessaoVersao:1,pagamentoCartaoAtivo:true,taxaCartaoCreditoAvistaPercent:3.8,taxaConvenienciaPix:0.5,descontoMensalidadePercentual:0,valorMensalidadeCustomizado:0,cancelamentoPlanoEstornoValor:0,cancelamentoPlanoDetalhes:{},tempoMedioEntregaMin:45,tempoAutoCancelamentoVitrineMin:6,maxPedidosPorEntregador:3,garcons:[]}, indexes:['CREATE UNIQUE INDEX idx_restaurantes_email ON restaurantes (email(191))','CREATE UNIQUE INDEX idx_restaurantes_slugIdentificador_unique ON restaurantes (slugIdentificador(191))']},
  CobrancaSaas:{table:'cobrancas_saas', fields:{restauranteId:id,planoCodigo:str,referencia:str,vencimento:date,valorPlano:money,descontoPercentual:money,descontoValor:money,valorFinal:money,status:str,mpPaymentId:str,qrCode:txt,qrCodeBase64:txt,pixCopiaECola:txt,pagoEm:date,geradoEm:date,estornoStatus:str,estornoValor:money,estornoEm:date,estornoErro:txt,estornoDetalhes:json,metadata:json}, defaults:{status:'pendente',valorPlano:0,descontoPercentual:0,descontoValor:0,valorFinal:0,estornoValor:0,estornoDetalhes:{},metadata:{},geradoEm:new Date()}, indexes:['CREATE INDEX idx_cobrancas_saas_restaurante ON cobrancas_saas (restauranteId)','CREATE INDEX idx_cobrancas_saas_payment ON cobrancas_saas (mpPaymentId(191))','CREATE INDEX idx_cobrancas_saas_status ON cobrancas_saas (status(32))']},
  Produto:{table:'produtos', fields:{restaurante:id,categoria:id,nome:str,descricao:txt,preco:money,imagem:txt,ativo:bool,ordem:num,tempoPreparoMin:num,destaque:bool,ativoVitrine:bool,imprimeNaCozinha:bool,mercadoPagoCategoryId:str,extras:json,estoque:json,sabores:json,bordas:json,adicionais:json,complementos:json,tipo:str,tipoItem:str,pizzaMultisabor:bool,maxSabores:num,calculoPrecoPor:str,disponivel:bool}, defaults:{ativo:true,ativoVitrine:true,disponivel:true,destaque:false,ordem:0,extras:[],tipoItem:'comum',pizzaMultisabor:false,maxSabores:1,calculoPrecoPor:'maior'}, indexes:['CREATE INDEX idx_produtos_restaurante ON produtos (restaurante)','CREATE INDEX idx_produtos_categoria ON produtos (categoria)']},
  CategoriaProduto:{table:'categorias_produto', fields:{restaurante:id,nome:str,slug:str,permiteSabores:bool,maxSabores:num,permiteBordas:bool,permiteAdicionais:bool,permiteComplementos:bool,saboresDisponiveis:json,bordasDisponiveis:json,adicionaisDisponiveis:json,complementosDisponiveis:json,ordem:num,tiposExtras:json,ativa:bool,pizzaMultisabor:bool,calculoPrecoPor:str}, defaults:{ativa:true,ordem:0,maxSabores:1,tiposExtras:[],saboresDisponiveis:[],bordasDisponiveis:[],adicionaisDisponiveis:[],complementosDisponiveis:[],calculoPrecoPor:'maior'}, indexes:['CREATE INDEX idx_categorias_restaurante ON categorias_produto (restaurante)']},
  Pedido:{table:'pedidos', fields:{numeroPedido:str,restaurante:id,cliente:id,entregador:id,mesaId:id,mesaNumero:str,nomeCliente:str,telefoneCliente:str,enderecoCliente:txt,itens:json,total:money,valorTotal:{...money,column:'total'},taxaEntrega:money,formaPagamento:str,formadePagamento:{...str,column:'formaPagamento'},status:str,statusPagamento:str,origem:str,observacao:txt,pagamento:json,pagamentos:json,descontoValor:money,valorDesconto:money,totalBruto:money,valorPago:money,valorPendente:money,mpPaymentId:str,mpPreferenceId:str,qrCode:txt,qrCodeBase64:txt,pixCopiaECola:txt,garcomId:str,garcomNome:str,recebidoPor:str,recebidoPorNome:str,fechadoPor:str,fechadoPorNome:str,criadoPor:str,criadoPorNome:str,criadoEm:date,pagoEm:date,aceitoEm:date,emProducaoEm:date,emEntregaEm:date,statusAtualizadoEm:date,entregueEm:date,canceladoEm:date,motivoCancelamento:txt,canceladoPor:str,canceladoPorRole:str,cancelamentoTipo:str,valorCancelado:money,itensCancelados:json,pedidoOriginalSnapshot:json,estornoStatus:str,estornoValor:money,estornoEm:date,estornoErro:txt,estornoDetalhes:json,dataOperacional:str,caixaSessaoId:id,operadorCaixaId:id,operadorCaixaNome:str}, defaults:{status:'pendente',statusPagamento:'pendente',origem:'delivery',itens:[],pagamentos:[],itensCancelados:[],total:0,valorTotal:0,descontoValor:0,valorDesconto:0,totalBruto:0,valorPago:0,valorPendente:0,valorCancelado:0,estornoValor:0,taxaEntrega:0,criadoEm:new Date()} , indexes:['CREATE INDEX idx_pedidos_restaurante ON pedidos (restaurante)','CREATE INDEX idx_pedidos_restaurante_criado ON pedidos (restaurante, criadoEm)','CREATE INDEX idx_pedidos_restaurante_status_criado ON pedidos (restaurante, status(32), criadoEm)','CREATE INDEX idx_pedidos_caixa ON pedidos (caixaSessaoId)','CREATE INDEX idx_pedidos_status ON pedidos (status(191))','CREATE INDEX idx_pedidos_entregador ON pedidos (entregador)']},
  Cliente:{table:'clientes', fields:{nome:str,telefone:str,email:str,enderecos:json}, defaults:{enderecos:[]}, indexes:['CREATE UNIQUE INDEX idx_clientes_telefone ON clientes (telefone(191))']},
  Entregador:{table:'entregadores', fields:{nome:str,email:str,senha:str,cpf:str,restaurante:id,localizacao:json,entregas:json,disponivel:bool,status:bool,statusConta:str,expoPushToken:txt}, defaults:{disponivel:true,status:true,statusConta:'ativo',entregas:[]}, indexes:['CREATE UNIQUE INDEX idx_entregadores_email ON entregadores (email(191))','CREATE UNIQUE INDEX idx_entregadores_cpf ON entregadores (cpf(191))','CREATE INDEX idx_entregadores_restaurante ON entregadores (restaurante)']},
  EntregadorOnline:{table:'entregadores_online', fields:{entregadorId:id,restauranteId:id,dataEntrada:date,dia:str,online:bool,localizacao:json}, defaults:{online:true,dataEntrada:new Date()}, indexes:['CREATE INDEX idx_entregadores_online_restaurante ON entregadores_online (restauranteId)']},
  Mesa:{table:'mesas', fields:{numero:str,restauranteId:id,qrCodeIdentifier:str,status:str,pedidoAtualId:id,sessaoToken:str,sessaoExpiraEm:date,sessaoInicialExpiraEm:date,ocupadaDesde:date,ultimaFechadaEm:date,ultimaPermanenciaSegundos:num}, defaults:{status:'livre',ultimaPermanenciaSegundos:0}, indexes:['CREATE UNIQUE INDEX idx_mesas_qr ON mesas (qrCodeIdentifier(191))','CREATE INDEX idx_mesas_restaurante ON mesas (restauranteId)','CREATE UNIQUE INDEX idx_mesas_restaurante_numero ON mesas (restauranteId, numero(191))']},
  PedidoMesa:{table:'pedidos_mesa', fields:{mesaId:id,mesaNumero:str,restauranteId:id,itens:json,valorTotal:money,status:str}, defaults:{itens:[],valorTotal:0,status:'aberto'}, indexes:['CREATE INDEX idx_pedidos_mesa_restaurante ON pedidos_mesa (restauranteId)']},
  Frete:{table:'fretes', fields:{restaurante:id,tipo:str,taxaFixa:money,valorPorKm:money,raioKm:num,faixasRaio:json,areas:json,ativo:bool}, defaults:{tipo:'raio',faixasRaio:[],areas:[],ativo:true}, indexes:['CREATE UNIQUE INDEX idx_fretes_restaurante_unique ON fretes (restaurante)']},
  Insumo:{table:'insumos', fields:{restauranteId:id,nome:str,unidadePadrao:str,baseUnit:str,quantidadeBase:{...num,column:'estoqueAtualBase'},minimoBase:{...num,column:'estoqueMinimoBase'},costBase:{...money,column:'custoMedioBase'},estoqueAtualBase:{...num,column:'estoqueAtualBase'},estoqueMinimoBase:{...num,column:'estoqueMinimoBase'},custoMedioBase:{...money,column:'custoMedioBase'},ativo:bool}, defaults:{ativo:true,quantidadeBase:0,minimoBase:0,costBase:0,estoqueAtualBase:0,estoqueMinimoBase:0,custoMedioBase:0}, indexes:['CREATE INDEX idx_insumos_restaurante ON insumos (restauranteId)']},
  MovimentoEstoque:{table:'movimentos_estoque', fields:{restauranteId:id,insumoId:id,tipo:str,quantidadeBase:num,custoUnitarioBase:money,origem:str,referenciaId:id,observacao:txt,data:date}, defaults:{data:new Date()}, indexes:['CREATE INDEX idx_movimentos_restaurante ON movimentos_estoque (restauranteId)','CREATE INDEX idx_movimentos_insumo ON movimentos_estoque (insumoId)']},
  Receita:{table:'receitas', fields:{restauranteId:id,nome:str,itens:json,ativo:bool}, defaults:{itens:[],ativo:true}, indexes:['CREATE INDEX idx_receitas_restaurante ON receitas (restauranteId)']},
  OAuthState:{table:'oauth_states', fields:{state:str,restauranteId:id,provider:str,codeVerifier:txt,redirectUri:txt,expiresAt:date,usado:bool}, defaults:{usado:false}, indexes:['CREATE UNIQUE INDEX idx_oauth_state ON oauth_states (state(191))']},
  ImagemFavorita:{table:'imagens_favoritas', fields:{restauranteId:id,url:txt,tipo:str,metadata:json,ativo:bool}, defaults:{ativo:true,metadata:{}}, indexes:['CREATE INDEX idx_imagens_restaurante ON imagens_favoritas (restauranteId)']},
  Adicional:{table:'adicionais', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_adicionais_produto ON adicionais (produto)']},
  Borda:{table:'bordas', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_bordas_produto ON bordas (produto)']},
  Complemento:{table:'complementos', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_complementos_produto ON complementos (produto)']},
  Sabor:{table:'sabores', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_sabores_produto ON sabores (produto)']},
  OperadorCaixa:{table:'operadores_caixa', fields:{restauranteId:id,nome:str,apelido:str,pin:str,ativo:bool,observacao:txt,permissoes:json}, defaults:{ativo:true,permissoes:{}}, indexes:['CREATE INDEX idx_operadores_caixa_restaurante ON operadores_caixa (restauranteId)','CREATE INDEX idx_operadores_caixa_nome ON operadores_caixa (nome(191))']},
  CaixaSessao:{table:'caixa_sessoes', fields:{restauranteId:id,operadorId:id,operadorNome:str,status:str,dataOperacional:str,saldoInicial:money,totalDinheiro:money,totalPix:money,totalCredito:money,totalDebito:money,totalOnline:money,totalOutros:money,totalVendas:money,totalPedidos:num,totalSangrias:money,totalSuprimentos:money,totalEsperadoDinheiro:money,saldoFinalInformado:money,observacaoAbertura:txt,observacaoFechamento:txt,abertoEm:date,fechadoEm:date,fechadoPor:str}, defaults:{status:'aberto',saldoInicial:0,totalDinheiro:0,totalPix:0,totalCredito:0,totalDebito:0,totalOnline:0,totalOutros:0,totalVendas:0,totalPedidos:0,totalSangrias:0,totalSuprimentos:0,totalEsperadoDinheiro:0}, indexes:['CREATE INDEX idx_caixa_sessoes_restaurante ON caixa_sessoes (restauranteId)','CREATE INDEX idx_caixa_sessoes_status ON caixa_sessoes (status(191))','CREATE INDEX idx_caixa_sessoes_data ON caixa_sessoes (dataOperacional(191))']},
  AuditLog:{table:'audit_logs', fields:{restauranteId:id,usuarioId:str,usuarioNome:str,role:str,acao:str,entidade:str,entidadeId:str,metodo:str,rota:txt,ip:str,userAgent:txt,detalhes:json,criadoEm:date}, defaults:{detalhes:{},criadoEm:new Date()}, indexes:['CREATE INDEX idx_audit_restaurante ON audit_logs (restauranteId)','CREATE INDEX idx_audit_acao ON audit_logs (acao(191))','CREATE INDEX idx_audit_data ON audit_logs (criadoEm)']},
  CaixaMovimento:{table:'caixa_movimentos', fields:{restauranteId:id,caixaSessaoId:id,operadorId:id,tipo:str,valor:money,formaPagamento:str,origem:str,pedidoId:id,referenciaPagamento:str,descricao:txt,data:date}, defaults:{valor:0,data:new Date(),formaPagamento:'dinheiro',origem:'caixa'}, indexes:['CREATE INDEX idx_caixa_movimentos_restaurante ON caixa_movimentos (restauranteId)','CREATE INDEX idx_caixa_movimentos_sessao ON caixa_movimentos (caixaSessaoId)','CREATE INDEX idx_caixa_movimentos_tipo ON caixa_movimentos (tipo(191))','CREATE INDEX idx_caixa_movimentos_referencia ON caixa_movimentos (referenciaPagamento(191))']},
  PushSubscription:{table:'push_subscriptions', fields:{restauranteId:id,usuarioId:str,role:str,endpoint:txt,endpointHash:str,p256dh:txt,auth:txt,expirationTime:date,plataforma:str,standalone:bool,userAgent:txt,ativo:bool,ultimaSincronizacaoEm:date,ultimoSucessoEm:date,ultimaFalhaEm:date,falhasConsecutivas:num,ultimoErro:txt}, defaults:{ativo:true,standalone:false,falhasConsecutivas:0,ultimaSincronizacaoEm:new Date()}, indexes:['CREATE UNIQUE INDEX idx_push_endpoint_hash ON push_subscriptions (endpointHash(64))','CREATE INDEX idx_push_restaurante_ativo ON push_subscriptions (restauranteId, ativo)']}
};
