const money={type:'DECIMAL(12,2)',kind:'number'}, num={type:'DOUBLE',kind:'number'}, bool={type:'TINYINT(1)',kind:'boolean'}, str={type:'VARCHAR(255)'}, txt={type:'TEXT'}, date={type:'DATETIME',kind:'date'}, id={type:'VARCHAR(24)',kind:'id'}, json={type:'LONGTEXT',kind:'json',json:true};
module.exports = {
  Restaurante:{table:'restaurantes', fields:{nome:str,email:str,senha:str,cnpj:str,enderecoCep:str,enderecoRua:str,enderecoNumero:str,enderecoBairro:str,enderecoCidade:str,enderecoEstado:str,telefone:str,logoUrl:txt,logoSlug:str,horariosFuncionamento:json,tempoMedioEntregaMin:num,maxPedidosPorEntregador:num,pedidosPorEntregador:num,anotaaiStatus:bool,anotaaiUrl:txt,anotaaiIdentificador:str,anotaaiToken:txt,ifoodStatus:bool,ifoodIdentificador:str,ifoodPrecisaConfirmacao:bool,ifoodIgnorarPronto:bool,ifood:json,localizacao:json,statusBot:json,ativo:bool,mensagensPersonalizadas:json,chavePix:str,recipient_id:str,mercadoPago:json,pagamentoCartaoAtivo:bool,taxaCartaoCreditoAvistaPercent:money,garcons:json,plano:str,slugIdentificador:str,dataCadastro:date}, defaults:{ativo:true,plano:'anual',pagamentoCartaoAtivo:true,taxaCartaoCreditoAvistaPercent:3.8,tempoMedioEntregaMin:45,maxPedidosPorEntregador:3,garcons:[]}, indexes:['CREATE UNIQUE INDEX idx_restaurantes_email ON restaurantes (email(191))','CREATE INDEX idx_restaurantes_slug ON restaurantes (slugIdentificador(191))']},
  Produto:{table:'produtos', fields:{restaurante:id,categoria:id,nome:str,descricao:txt,preco:money,imagem:txt,ativo:bool,ordem:num,tempoPreparoMin:num,destaque:bool,imprimeNaCozinha:bool,mercadoPagoCategoryId:str,extras:json,estoque:json,sabores:json,bordas:json,adicionais:json,complementos:json,tipo:str,disponivel:bool}, defaults:{ativo:true,disponivel:true,destaque:false,ordem:0,extras:[]}, indexes:['CREATE INDEX idx_produtos_restaurante ON produtos (restaurante)','CREATE INDEX idx_produtos_categoria ON produtos (categoria)']},
  CategoriaProduto:{table:'categorias_produto', fields:{restaurante:id,nome:str,slug:str,permiteSabores:bool,maxSabores:num,permiteBordas:bool,permiteAdicionais:bool,permiteComplementos:bool,saboresDisponiveis:json,bordasDisponiveis:json,adicionaisDisponiveis:json,complementosDisponiveis:json,ordem:num,tiposExtras:json,ativa:bool,pizzaMultisabor:bool,calculoPrecoPor:str}, defaults:{ativa:true,ordem:0,maxSabores:1,tiposExtras:[],saboresDisponiveis:[],bordasDisponiveis:[],adicionaisDisponiveis:[],complementosDisponiveis:[],calculoPrecoPor:'maior'}, indexes:['CREATE INDEX idx_categorias_restaurante ON categorias_produto (restaurante)']},
  Pedido:{table:'pedidos', fields:{numeroPedido:str,restaurante:id,cliente:id,entregador:id,mesaId:id,mesaNumero:str,nomeCliente:str,telefoneCliente:str,enderecoCliente:txt,itens:json,total:money,valorTotal:{...money,column:'total'},taxaEntrega:money,formaPagamento:str,formadePagamento:{...str,column:'formaPagamento'},status:str,statusPagamento:str,origem:str,observacao:txt,pagamento:json,pagamentos:json,valorPago:money,valorPendente:money,mpPaymentId:str,mpPreferenceId:str,qrCode:txt,qrCodeBase64:txt,pixCopiaECola:txt,garcomId:str,garcomNome:str,recebidoPor:str,recebidoPorNome:str,fechadoPor:str,fechadoPorNome:str,criadoPor:str,criadoPorNome:str,criadoEm:date,pagoEm:date,entregueEm:date,canceladoEm:date}, defaults:{status:'pendente',statusPagamento:'pendente',origem:'delivery',itens:[],pagamentos:[],total:0,valorTotal:0,valorPago:0,valorPendente:0,taxaEntrega:0,criadoEm:new Date()} , indexes:['CREATE INDEX idx_pedidos_restaurante ON pedidos (restaurante)','CREATE INDEX idx_pedidos_status ON pedidos (status(191))','CREATE INDEX idx_pedidos_entregador ON pedidos (entregador)']},
  Cliente:{table:'clientes', fields:{nome:str,telefone:str,email:str,enderecos:json}, defaults:{enderecos:[]}, indexes:['CREATE UNIQUE INDEX idx_clientes_telefone ON clientes (telefone(191))']},
  Entregador:{table:'entregadores', fields:{nome:str,email:str,senha:str,cpf:str,restaurante:id,localizacao:json,entregas:json,disponivel:bool,status:bool,statusConta:str,expoPushToken:txt}, defaults:{disponivel:true,status:true,statusConta:'ativo',entregas:[]}, indexes:['CREATE UNIQUE INDEX idx_entregadores_email ON entregadores (email(191))','CREATE UNIQUE INDEX idx_entregadores_cpf ON entregadores (cpf(191))','CREATE INDEX idx_entregadores_restaurante ON entregadores (restaurante)']},
  EntregadorOnline:{table:'entregadores_online', fields:{entregadorId:id,restauranteId:id,dataEntrada:date,dia:str,online:bool,localizacao:json}, defaults:{online:true,dataEntrada:new Date()}, indexes:['CREATE INDEX idx_entregadores_online_restaurante ON entregadores_online (restauranteId)']},
  Mesa:{table:'mesas', fields:{numero:str,restauranteId:id,qrCodeIdentifier:str,status:str,pedidoAtualId:id,sessaoToken:str,sessaoExpiraEm:date,sessaoInicialExpiraEm:date,ocupadaDesde:date,ultimaFechadaEm:date,ultimaPermanenciaSegundos:num}, defaults:{status:'livre',ultimaPermanenciaSegundos:0}, indexes:['CREATE UNIQUE INDEX idx_mesas_qr ON mesas (qrCodeIdentifier(191))','CREATE INDEX idx_mesas_restaurante ON mesas (restauranteId)','CREATE UNIQUE INDEX idx_mesas_restaurante_numero ON mesas (restauranteId, numero(191))']},
  PedidoMesa:{table:'pedidos_mesa', fields:{mesaId:id,mesaNumero:str,restauranteId:id,itens:json,valorTotal:money,status:str}, defaults:{itens:[],valorTotal:0,status:'aberto'}, indexes:['CREATE INDEX idx_pedidos_mesa_restaurante ON pedidos_mesa (restauranteId)']},
  Frete:{table:'fretes', fields:{restaurante:id,tipo:str,taxaFixa:money,valorPorKm:money,raioKm:num,areas:json,ativo:bool}, defaults:{areas:[],ativo:true}, indexes:['CREATE INDEX idx_fretes_restaurante ON fretes (restaurante)']},
  Insumo:{table:'insumos', fields:{restauranteId:id,nome:str,unidadePadrao:str,baseUnit:str,quantidadeBase:{...num,column:'estoqueAtualBase'},minimoBase:{...num,column:'estoqueMinimoBase'},costBase:{...money,column:'custoMedioBase'},estoqueAtualBase:{...num,column:'estoqueAtualBase'},estoqueMinimoBase:{...num,column:'estoqueMinimoBase'},custoMedioBase:{...money,column:'custoMedioBase'},ativo:bool}, defaults:{ativo:true,quantidadeBase:0,minimoBase:0,costBase:0,estoqueAtualBase:0,estoqueMinimoBase:0,custoMedioBase:0}, indexes:['CREATE INDEX idx_insumos_restaurante ON insumos (restauranteId)']},
  MovimentoEstoque:{table:'movimentos_estoque', fields:{restauranteId:id,insumoId:id,tipo:str,quantidadeBase:num,custoUnitarioBase:money,origem:str,referenciaId:id,observacao:txt,data:date}, defaults:{data:new Date()}, indexes:['CREATE INDEX idx_movimentos_restaurante ON movimentos_estoque (restauranteId)','CREATE INDEX idx_movimentos_insumo ON movimentos_estoque (insumoId)']},
  Receita:{table:'receitas', fields:{restauranteId:id,nome:str,itens:json,ativo:bool}, defaults:{itens:[],ativo:true}, indexes:['CREATE INDEX idx_receitas_restaurante ON receitas (restauranteId)']},
  OAuthState:{table:'oauth_states', fields:{state:str,restauranteId:id,provider:str,codeVerifier:txt,redirectUri:txt,expiresAt:date,usado:bool}, defaults:{usado:false}, indexes:['CREATE UNIQUE INDEX idx_oauth_state ON oauth_states (state(191))']},
  ImagemFavorita:{table:'imagens_favoritas', fields:{restauranteId:id,url:txt,tipo:str,metadata:json,ativo:bool}, defaults:{ativo:true,metadata:{}}, indexes:['CREATE INDEX idx_imagens_restaurante ON imagens_favoritas (restauranteId)']},
  Adicional:{table:'adicionais', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_adicionais_produto ON adicionais (produto)']},
  Borda:{table:'bordas', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_bordas_produto ON bordas (produto)']},
  Complemento:{table:'complementos', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_complementos_produto ON complementos (produto)']},
  Sabor:{table:'sabores', fields:{produto:id,nome:str,preco:money}, defaults:{preco:0}, indexes:['CREATE INDEX idx_sabores_produto ON sabores (produto)']}
};
